# Generated by Django 5.1.3 on 2024-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProf',
        ),
    ]
