# Generated by Django 5.1.3 on 2024-11-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0002_rename_userprofile_userprof'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProf',
            new_name='UserProfile',
        ),
    ]
