# Generated by Django 5.1.3 on 2024-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0003_rename_userprof_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('physical_details', models.TextField(blank=True, null=True)),
                ('date_of_disappearance', models.DateField()),
                ('location_of_disappearance', models.CharField(max_length=255)),
                ('contact_details', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='missing_persons_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
