# Generated by Django 5.0.7 on 2024-12-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0006_remove_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
