# Generated by Django 5.0.7 on 2024-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0007_remove_userprofile_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
