# Generated by Django 5.0.7 on 2024-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0008_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Your Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('found_person_name', models.CharField(max_length=100, verbose_name='Name of Found Person')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Date Reported')),
            ],
        ),
    ]
