# Generated by Django 5.0.7 on 2024-12-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abducted', '0009_foundperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonreport',
            name='phone',
            field=models.PositiveBigIntegerField(default='0712345678', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='username',
            field=models.CharField(default='your name', max_length=100, unique=True),
        ),
    ]
